---
- include_vars: "{{ansible_os_family}}-vars.yml"
- include_tasks: "{{ansible_os_family}}.yml"

- name: Start ldap service
  service:
    name: slapd
    state: started

- name: Register encripted password
  command: slappasswd -s "{{ldap_password}}"
  register: ldap_encripted_password

- name: Copy db templates
  template:
    src: "{{item}}"
    dest: /tmp
  with_items:
    - db.ldif
    - base.ldif

- name: Load ddbb template into ldap
  command: ldapmodify -Y EXTERNAL  -H ldapi:/// -f /tmp/db.ldif

- name: Copy the example ddbb
  copy:
    src: "{{dbconfig_path}}"
    dest: /var/lib/ldap/DB_CONFIG
    remote_src: yes
    owner: root
    group: root

- name: Load some schemas (ignoring duplicate entries error for idempotence)
  command: "ldapadd -Y EXTERNAL -H ldapi:/// -f {{schema_path}}/{{item}}"
  register: ldap_result_code
  failed_when: ldap_result_code.rc not in [0,80]
  changed_when: ldap_result_code.rc not in [0,80]
  with_items:
    - cosine.ldif
    - nis.ldif
    - inetorgperson.ldif

#- name: Load data (ignoring duplicate entries error for idempotence)
#  command: "ldapadd -x -D 'cn={{ldap_username}},{{ldap_basedn}}' -w {{ldap_password}} -f /tmp/base.ldif"
#  register: ldap_result_code
#  failed_when: ldap_result_code.rc not in [0,68]
#  changed_when: ldap_result_code.rc not in [0,68]

- name: Load groups data
  ldap_entry:
    server_uri: ldap://localhost:10389
    bind_dn: cn=admin,dc=golili,dc=net
    bind_pw: secret
    dn: ou=groups,dc=golili,dc=net
    objectclass:
      - organizationalUnit
      - top
