---
- name: Install required packages
  yum:
    name: "{{item}}"
    state: present
    validate_certs: no
    disable_gpg_check: yes
  with_items:
    - openldap
    - openldap-servers
    - openldap-clients
    - python-ldap

