---
- name: Install required packages
  yum:
    state: present
    validate_certs: no
    enablerepo: powertools
    disable_gpg_check: yes
    name:
    - openldap
    - openldap-servers
    - openldap-clients
    - python-ldap
